/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_chunk_header = 1,
  sym_r_line = 2,
  sym_chunk_end = 3,
  sym_text_line = 4,
  sym_source_file = 5,
  sym_code_chunk = 6,
  sym_chunk_body = 7,
  aux_sym_source_file_repeat1 = 8,
  aux_sym_chunk_body_repeat1 = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_chunk_header] = "chunk_header",
  [sym_r_line] = "r_line",
  [sym_chunk_end] = "chunk_end",
  [sym_text_line] = "text_line",
  [sym_source_file] = "source_file",
  [sym_code_chunk] = "code_chunk",
  [sym_chunk_body] = "chunk_body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_chunk_body_repeat1] = "chunk_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_chunk_header] = sym_chunk_header,
  [sym_r_line] = sym_r_line,
  [sym_chunk_end] = sym_chunk_end,
  [sym_text_line] = sym_text_line,
  [sym_source_file] = sym_source_file,
  [sym_code_chunk] = sym_code_chunk,
  [sym_chunk_body] = sym_chunk_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_chunk_body_repeat1] = aux_sym_chunk_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_chunk_header] = {
    .visible = true,
    .named = true,
  },
  [sym_r_line] = {
    .visible = true,
    .named = true,
  },
  [sym_chunk_end] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_code_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_chunk_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chunk_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '<') ADVANCE(10);
      if (lookahead == '@') ADVANCE(8);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '@') ADVANCE(8);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '<') ADVANCE(17);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_chunk_header);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_r_line);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_chunk_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_chunk_end);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_text_line);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '>') ADVANCE(12);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '>') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '>') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '>') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_chunk_header] = ACTIONS(1),
    [sym_r_line] = ACTIONS(1),
    [sym_chunk_end] = ACTIONS(1),
    [sym_text_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(9),
    [sym_code_chunk] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_chunk_header] = ACTIONS(5),
    [sym_text_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_chunk_header,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_text_line,
    STATE(3), 2,
      sym_code_chunk,
      aux_sym_source_file_repeat1,
  [14] = 4,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_chunk_header,
    ACTIONS(18), 1,
      sym_text_line,
    STATE(3), 2,
      sym_code_chunk,
      aux_sym_source_file_repeat1,
  [28] = 4,
    ACTIONS(21), 1,
      sym_r_line,
    ACTIONS(23), 1,
      sym_chunk_end,
    STATE(6), 1,
      aux_sym_chunk_body_repeat1,
    STATE(10), 1,
      sym_chunk_body,
  [41] = 2,
    ACTIONS(27), 1,
      sym_text_line,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_chunk_header,
  [49] = 3,
    ACTIONS(29), 1,
      sym_r_line,
    ACTIONS(31), 1,
      sym_chunk_end,
    STATE(8), 1,
      aux_sym_chunk_body_repeat1,
  [59] = 2,
    ACTIONS(35), 1,
      sym_text_line,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_chunk_header,
  [67] = 3,
    ACTIONS(37), 1,
      sym_r_line,
    ACTIONS(40), 1,
      sym_chunk_end,
    STATE(8), 1,
      aux_sym_chunk_body_repeat1,
  [77] = 1,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
  [81] = 1,
    ACTIONS(44), 1,
      sym_chunk_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 41,
  [SMALL_STATE(6)] = 49,
  [SMALL_STATE(7)] = 59,
  [SMALL_STATE(8)] = 67,
  [SMALL_STATE(9)] = 77,
  [SMALL_STATE(10)] = 81,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_chunk, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_chunk, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chunk_body, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_chunk, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_chunk, 3, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_chunk_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chunk_body_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sweave(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sweave",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
